select * from customer

--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount)
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(Avg(review_rating :: numeric),2) as average_rating
from customer
group by item_purchased
order by average_rating desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, ROUND(Avg(purchase_amount),2)
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
ROUND(Avg(purchase_amount)) as avg_spend,
ROUND(Sum(purchase_amount)) as total_revenue
from customer
group by subscription_status 
order by avg_spend, total_revenue

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of customers in each segment.

with customer_type as(
select customer_id, previous_purchases
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segement
from customer
)

select customer_segement, COUNT(*) as "Number of Customer"
--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;